var en = {
    'inicio': 'Home',
    'area': 'Occupation area',
    'quem': 'About Us',
    'quem_txt' : 'We are a company specialized in providing services in the environmental area, 13 years in the market, serving public and private companies operating in the domestic market. It is with the care and technical expertise of a highly qualified team that we design the most effective solutions appropriate, environmentally sound and sustainable, resulting in social benefits and successful initiatives in the Brazilian socioeconomic scenario. Our team monitors all phases of the project and acts in line with environmental policies and standards. in force. We have gathered our technical expertise and excellent relationship with Environmental agencies and institutions to become reference in environmental management, having nationally recognized projects in the areas of Licensing Environmental, Environmental Feasibility Studies and Environmental Management of Works. Here, we join efforts to preserve Brazil\'s environmental heritage, We multiply innovative ideas to reduce environmental impacts and share with our customers to contribute to the growth of the country, delivering large installed works, as: Hydroelectric, Wind Complexes, Port Terminals, Highways and Transmission Lines.',
    'pol': 'Quality policy',
    'pol_txt' : 'Innovate and apply high quality standards in the provision of environmental solutions services, complying with legal and regulatory requirements, respecting the environment and meeting the requirements established by our customers, employees, shareholders, partners and licensing bodies and stakeholders in order to generate the less impact on nature, maintaining a commitment to pollution prevention, environmental protection and the continuous improvement of our processes and services.',
    'ar': 'Areas of expertise',
    'contato': 'Contacts',
    'servicos': 'Services',
    'work': 'Work with us',
    'experiencia' : 'Experience',
    'experiencia_txt' : 'Another decade of experience in environmental consulting',
    'adj' : 'Adjacency',
    'adj_txt' : 'Proximity to key environmental agencies and stakeholders',
    'cobertura' : 'Coverage',
    'cobertura_txt' : 'Performance in all regions of the country',
    'qualificacao' : 'Qualification',
    'qualificacao_txt' : 'Specialized multidisciplinary team and ISO 9001 and ISO 14001 certified company',
    'inovacao' : 'Innovation',
    'inovacao_txt' : 'Development of own technologies',
    'produtos' : 'Custom Products',
    'produtos_txt' : 'Fully optimized solutions for the needs of each project.',
    'anterior' : 'previous',
    'proximo' : 'next',
    'missao' : 'Mission',
    'missao_txt' : 'Deliver innovative environmental solutions that ensure safety and credibility, adding value to society.',
    'visao' : 'vision',
    'visao_txt' : 'Being a solid company, with efficient processes and happy people, exceeding expectations in our relationships.',
    'valores' : 'Values',
    "valores_txt" : "- High performance and Innovation;\n - Ethics and Transparency;\n - Simplicity and Respect;\n - Perseverance and Resilience.",
    'principais' :'main areas of expertise',
    'infra' :'Infrastructure and Transportation',
    'infra_txt' : 'We have solid experience in environmental licensing and supervision of transport infrastructure works such as: Highways, Waterways and Port Terminals. We accompany and support the licensing activities of the support areas of these types of projects, such as: mineral deposits, construction sites, asphalt plants, loan areas and drop-offs.',
    'energia' : 'Energy',
    'energia_txt' : 'We participate in several licensing processes related to the Electricity Sector, conducting environmental impact studies and implementation of control and monitoring programs for generation and transmission projects, such as: Small Hydroelectric Plants (SHPs), Hydroelectric Plants (UHEs), Complexes Wind Power, Transmission Lines and Power Substations.',
    'industria' : 'Industry',
    'industria_txt' : 'We operate in the environmental licensing of industrial units of all sizes and branches, proposing actions to mitigate environmental impacts and making production processes environmentally viable. We work in all stages of the process, from the feasibility study of the activity in the proposed location, to conducting the entire environmental licensing process - preparing the necessary studies and performing the intermediary between the entrepreneur and the Environmental    agencies - following with the step monitoring programs throughout the operation of the project.',
    'mineracao' : 'Mining',
    'mineracao_txt' : 'We develop works focused on environmental licensing, environmental control and monitoring. Monitoring consists of assessments of water quality, noise, terrain vibrations, as well as the elaboration of recovery programs for degraded areas.',
    'proj' : 'Custom Projects',
    'proj_txt' : 'We set up custom projects, adapting the peculiarities of the project presented, forming a unique action plan.',
    'monitoramento' : 'ENVIRONMENTAL MONITORING AND CONTROL',
    'monitoramento_txt' : 'We carry out the whole environmental monitoring process by means of data collection, study and continuous and systematic monitoring of all environmental variables, which directly or indirectly, exercise influence on the environment. Concerned about all these variables, either environmental, social or institutional, our team is prepared to carry out a wide range of environmental-oriented actions throughout the deployment and operation of the project, related to environmental supervision of engineering works and implementation of environmental plans and programs in the areas of environmental education, media, monitoring of social and environmental indicators, wildlife rescue and recovery, monitoring of water quality, among other activities.',
    'licenciamento' : 'ENVIRONMENTAL LICENSING',
    'licenciamento_txt' : 'We carry out studies, reports, environmental projects as well as the management of the licensing process, in line with environmental legislation, from the initial phase to the expedition of preliminary licenses, licenses for the installation and operation of the project, in addition to monitoring the environmental restrictions required by competent bodies. Environmental licensing is a legal obligation prior to the installation of any project or activity potentially polluting or detrimental to the environment, and one of its most significant features is social participation in decision-making, through Public Hearings, which are a part of the process.',
    'auditoria' : 'AUDITING AND ENVIRONMENTAL MANAGEMENT',
    'auditoria_txt' : 'We customize the entire process for environmental management and licensing of projects with competent environmental bodies. We work on the operation, supervision and execution of environmental initiatives, in addition to planning activities in the pursuit of environmental quality management and project excellence through the implementation of procedures that make the ISO14001 certificate possible.',
    'consultoria' : 'CONSULTANCY AND ENVIRONMENTAL ENGINEERING PROJECTS',
    'consultoria_txt' : 'We present proposals and provide consultancy services in accordance with the laws and regulations in force, for the development of engineering projects aimed at the treatment of sanitary and industrial effluents, atmospheric effluents, as well as storage and final disposal of solid waste.',
    'estudos' : 'ENVIRONMENTAL FEASIBILITY STUDIES',
    'estudos_txt' : 'We provide clients with technical reports and budgeting of environmental costs after having carried out a preliminary survey, consisting of assessment of environmental constraints and significant impacts resulting from the implementation of a project. Our studies support entrepreneurs in the correct economic assessment of projects and propose optimization and cost reduction, in addition to assisting investors in energy auctions. We also perform environmental studies for Hydropower Inventory, Basic Design and Technical and Economic Feasibility Study.',
    'geoprocessamento' : 'GEOPROCESSING',
    'geoprocessamento_txt' : 'We use geoprocessing in environmental licensing and monitoring projects, providing clients with digital cartography, mapping, compilation, analysis, interpretation of satellite images and aerial photographs as well as production of thematic maps used in environmental studies, which assist in environmental analysis and management of projects. We also present information for decision-making on urban, rural, and environmental problems, conducting complex analysis by integrating data from various sources and creating geo-referenced databases for the client.',
    'fale' : 'Contact Us',
    'end_sede' : 'Address Head Office',
    'end_sede_txt' : '',
    'end_filial' : 'Address Branch',
    'end_filial_txt' : '',
    'tel_sede' : 'Telephone Head Office',
    'tel_filial' : 'Telephone Branch',
    'trabalhe_txt' : '',
    'enviar' : 'Submit',
    'links' : 'use the links',
    'tel' : 'telephone',
    'receba' : 'RECEIVE OUR NEWS',
    'receba_txt' : 'Stay on top of important news for our country and our planet.',
    'trabalhe_txt' : 'SEND YOUR CURRICULUM TO:',
    'trabalhe' : 'Work With us',



  }
